require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BoneMarrowTransplantationsController do

  # This should return the minimal set of attributes required to create a valid
  # BoneMarrowTransplantation. As you add validations to BoneMarrowTransplantation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BoneMarrowTransplantationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all bone_marrow_transplantations as @bone_marrow_transplantations" do
      bone_marrow_transplantation = BoneMarrowTransplantation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bone_marrow_transplantations).should eq([bone_marrow_transplantation])
    end
  end

  describe "GET show" do
    it "assigns the requested bone_marrow_transplantation as @bone_marrow_transplantation" do
      bone_marrow_transplantation = BoneMarrowTransplantation.create! valid_attributes
      get :show, {:id => bone_marrow_transplantation.to_param}, valid_session
      assigns(:bone_marrow_transplantation).should eq(bone_marrow_transplantation)
    end
  end

  describe "GET new" do
    it "assigns a new bone_marrow_transplantation as @bone_marrow_transplantation" do
      get :new, {}, valid_session
      assigns(:bone_marrow_transplantation).should be_a_new(BoneMarrowTransplantation)
    end
  end

  describe "GET edit" do
    it "assigns the requested bone_marrow_transplantation as @bone_marrow_transplantation" do
      bone_marrow_transplantation = BoneMarrowTransplantation.create! valid_attributes
      get :edit, {:id => bone_marrow_transplantation.to_param}, valid_session
      assigns(:bone_marrow_transplantation).should eq(bone_marrow_transplantation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BoneMarrowTransplantation" do
        expect {
          post :create, {:bone_marrow_transplantation => valid_attributes}, valid_session
        }.to change(BoneMarrowTransplantation, :count).by(1)
      end

      it "assigns a newly created bone_marrow_transplantation as @bone_marrow_transplantation" do
        post :create, {:bone_marrow_transplantation => valid_attributes}, valid_session
        assigns(:bone_marrow_transplantation).should be_a(BoneMarrowTransplantation)
        assigns(:bone_marrow_transplantation).should be_persisted
      end

      it "redirects to the created bone_marrow_transplantation" do
        post :create, {:bone_marrow_transplantation => valid_attributes}, valid_session
        response.should redirect_to(BoneMarrowTransplantation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bone_marrow_transplantation as @bone_marrow_transplantation" do
        # Trigger the behavior that occurs when invalid params are submitted
        BoneMarrowTransplantation.any_instance.stub(:save).and_return(false)
        post :create, {:bone_marrow_transplantation => {}}, valid_session
        assigns(:bone_marrow_transplantation).should be_a_new(BoneMarrowTransplantation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BoneMarrowTransplantation.any_instance.stub(:save).and_return(false)
        post :create, {:bone_marrow_transplantation => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bone_marrow_transplantation" do
        bone_marrow_transplantation = BoneMarrowTransplantation.create! valid_attributes
        # Assuming there are no other bone_marrow_transplantations in the database, this
        # specifies that the BoneMarrowTransplantation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BoneMarrowTransplantation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => bone_marrow_transplantation.to_param, :bone_marrow_transplantation => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested bone_marrow_transplantation as @bone_marrow_transplantation" do
        bone_marrow_transplantation = BoneMarrowTransplantation.create! valid_attributes
        put :update, {:id => bone_marrow_transplantation.to_param, :bone_marrow_transplantation => valid_attributes}, valid_session
        assigns(:bone_marrow_transplantation).should eq(bone_marrow_transplantation)
      end

      it "redirects to the bone_marrow_transplantation" do
        bone_marrow_transplantation = BoneMarrowTransplantation.create! valid_attributes
        put :update, {:id => bone_marrow_transplantation.to_param, :bone_marrow_transplantation => valid_attributes}, valid_session
        response.should redirect_to(bone_marrow_transplantation)
      end
    end

    describe "with invalid params" do
      it "assigns the bone_marrow_transplantation as @bone_marrow_transplantation" do
        bone_marrow_transplantation = BoneMarrowTransplantation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BoneMarrowTransplantation.any_instance.stub(:save).and_return(false)
        put :update, {:id => bone_marrow_transplantation.to_param, :bone_marrow_transplantation => {}}, valid_session
        assigns(:bone_marrow_transplantation).should eq(bone_marrow_transplantation)
      end

      it "re-renders the 'edit' template" do
        bone_marrow_transplantation = BoneMarrowTransplantation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BoneMarrowTransplantation.any_instance.stub(:save).and_return(false)
        put :update, {:id => bone_marrow_transplantation.to_param, :bone_marrow_transplantation => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bone_marrow_transplantation" do
      bone_marrow_transplantation = BoneMarrowTransplantation.create! valid_attributes
      expect {
        delete :destroy, {:id => bone_marrow_transplantation.to_param}, valid_session
      }.to change(BoneMarrowTransplantation, :count).by(-1)
    end

    it "redirects to the bone_marrow_transplantations list" do
      bone_marrow_transplantation = BoneMarrowTransplantation.create! valid_attributes
      delete :destroy, {:id => bone_marrow_transplantation.to_param}, valid_session
      response.should redirect_to(bone_marrow_transplantations_url)
    end
  end

end
