require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ChemoTherapiesController do

  # This should return the minimal set of attributes required to create a valid
  # ChemoTherapy. As you add validations to ChemoTherapy, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ChemoTherapiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all chemo_therapies as @chemo_therapies" do
      chemo_therapy = ChemoTherapy.create! valid_attributes
      get :index, {}, valid_session
      assigns(:chemo_therapies).should eq([chemo_therapy])
    end
  end

  describe "GET show" do
    it "assigns the requested chemo_therapy as @chemo_therapy" do
      chemo_therapy = ChemoTherapy.create! valid_attributes
      get :show, {:id => chemo_therapy.to_param}, valid_session
      assigns(:chemo_therapy).should eq(chemo_therapy)
    end
  end

  describe "GET new" do
    it "assigns a new chemo_therapy as @chemo_therapy" do
      get :new, {}, valid_session
      assigns(:chemo_therapy).should be_a_new(ChemoTherapy)
    end
  end

  describe "GET edit" do
    it "assigns the requested chemo_therapy as @chemo_therapy" do
      chemo_therapy = ChemoTherapy.create! valid_attributes
      get :edit, {:id => chemo_therapy.to_param}, valid_session
      assigns(:chemo_therapy).should eq(chemo_therapy)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ChemoTherapy" do
        expect {
          post :create, {:chemo_therapy => valid_attributes}, valid_session
        }.to change(ChemoTherapy, :count).by(1)
      end

      it "assigns a newly created chemo_therapy as @chemo_therapy" do
        post :create, {:chemo_therapy => valid_attributes}, valid_session
        assigns(:chemo_therapy).should be_a(ChemoTherapy)
        assigns(:chemo_therapy).should be_persisted
      end

      it "redirects to the created chemo_therapy" do
        post :create, {:chemo_therapy => valid_attributes}, valid_session
        response.should redirect_to(ChemoTherapy.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved chemo_therapy as @chemo_therapy" do
        # Trigger the behavior that occurs when invalid params are submitted
        ChemoTherapy.any_instance.stub(:save).and_return(false)
        post :create, {:chemo_therapy => {}}, valid_session
        assigns(:chemo_therapy).should be_a_new(ChemoTherapy)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ChemoTherapy.any_instance.stub(:save).and_return(false)
        post :create, {:chemo_therapy => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested chemo_therapy" do
        chemo_therapy = ChemoTherapy.create! valid_attributes
        # Assuming there are no other chemo_therapies in the database, this
        # specifies that the ChemoTherapy created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ChemoTherapy.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => chemo_therapy.to_param, :chemo_therapy => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested chemo_therapy as @chemo_therapy" do
        chemo_therapy = ChemoTherapy.create! valid_attributes
        put :update, {:id => chemo_therapy.to_param, :chemo_therapy => valid_attributes}, valid_session
        assigns(:chemo_therapy).should eq(chemo_therapy)
      end

      it "redirects to the chemo_therapy" do
        chemo_therapy = ChemoTherapy.create! valid_attributes
        put :update, {:id => chemo_therapy.to_param, :chemo_therapy => valid_attributes}, valid_session
        response.should redirect_to(chemo_therapy)
      end
    end

    describe "with invalid params" do
      it "assigns the chemo_therapy as @chemo_therapy" do
        chemo_therapy = ChemoTherapy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ChemoTherapy.any_instance.stub(:save).and_return(false)
        put :update, {:id => chemo_therapy.to_param, :chemo_therapy => {}}, valid_session
        assigns(:chemo_therapy).should eq(chemo_therapy)
      end

      it "re-renders the 'edit' template" do
        chemo_therapy = ChemoTherapy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ChemoTherapy.any_instance.stub(:save).and_return(false)
        put :update, {:id => chemo_therapy.to_param, :chemo_therapy => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested chemo_therapy" do
      chemo_therapy = ChemoTherapy.create! valid_attributes
      expect {
        delete :destroy, {:id => chemo_therapy.to_param}, valid_session
      }.to change(ChemoTherapy, :count).by(-1)
    end

    it "redirects to the chemo_therapies list" do
      chemo_therapy = ChemoTherapy.create! valid_attributes
      delete :destroy, {:id => chemo_therapy.to_param}, valid_session
      response.should redirect_to(chemo_therapies_url)
    end
  end

end
