require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CytostaticDrugGivensController do

  # This should return the minimal set of attributes required to create a valid
  # CytostaticDrugGiven. As you add validations to CytostaticDrugGiven, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CytostaticDrugGivensController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all cytostatic_drug_givens as @cytostatic_drug_givens" do
      cytostatic_drug_given = CytostaticDrugGiven.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cytostatic_drug_givens).should eq([cytostatic_drug_given])
    end
  end

  describe "GET show" do
    it "assigns the requested cytostatic_drug_given as @cytostatic_drug_given" do
      cytostatic_drug_given = CytostaticDrugGiven.create! valid_attributes
      get :show, {:id => cytostatic_drug_given.to_param}, valid_session
      assigns(:cytostatic_drug_given).should eq(cytostatic_drug_given)
    end
  end

  describe "GET new" do
    it "assigns a new cytostatic_drug_given as @cytostatic_drug_given" do
      get :new, {}, valid_session
      assigns(:cytostatic_drug_given).should be_a_new(CytostaticDrugGiven)
    end
  end

  describe "GET edit" do
    it "assigns the requested cytostatic_drug_given as @cytostatic_drug_given" do
      cytostatic_drug_given = CytostaticDrugGiven.create! valid_attributes
      get :edit, {:id => cytostatic_drug_given.to_param}, valid_session
      assigns(:cytostatic_drug_given).should eq(cytostatic_drug_given)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CytostaticDrugGiven" do
        expect {
          post :create, {:cytostatic_drug_given => valid_attributes}, valid_session
        }.to change(CytostaticDrugGiven, :count).by(1)
      end

      it "assigns a newly created cytostatic_drug_given as @cytostatic_drug_given" do
        post :create, {:cytostatic_drug_given => valid_attributes}, valid_session
        assigns(:cytostatic_drug_given).should be_a(CytostaticDrugGiven)
        assigns(:cytostatic_drug_given).should be_persisted
      end

      it "redirects to the created cytostatic_drug_given" do
        post :create, {:cytostatic_drug_given => valid_attributes}, valid_session
        response.should redirect_to(CytostaticDrugGiven.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cytostatic_drug_given as @cytostatic_drug_given" do
        # Trigger the behavior that occurs when invalid params are submitted
        CytostaticDrugGiven.any_instance.stub(:save).and_return(false)
        post :create, {:cytostatic_drug_given => {}}, valid_session
        assigns(:cytostatic_drug_given).should be_a_new(CytostaticDrugGiven)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CytostaticDrugGiven.any_instance.stub(:save).and_return(false)
        post :create, {:cytostatic_drug_given => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cytostatic_drug_given" do
        cytostatic_drug_given = CytostaticDrugGiven.create! valid_attributes
        # Assuming there are no other cytostatic_drug_givens in the database, this
        # specifies that the CytostaticDrugGiven created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CytostaticDrugGiven.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => cytostatic_drug_given.to_param, :cytostatic_drug_given => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested cytostatic_drug_given as @cytostatic_drug_given" do
        cytostatic_drug_given = CytostaticDrugGiven.create! valid_attributes
        put :update, {:id => cytostatic_drug_given.to_param, :cytostatic_drug_given => valid_attributes}, valid_session
        assigns(:cytostatic_drug_given).should eq(cytostatic_drug_given)
      end

      it "redirects to the cytostatic_drug_given" do
        cytostatic_drug_given = CytostaticDrugGiven.create! valid_attributes
        put :update, {:id => cytostatic_drug_given.to_param, :cytostatic_drug_given => valid_attributes}, valid_session
        response.should redirect_to(cytostatic_drug_given)
      end
    end

    describe "with invalid params" do
      it "assigns the cytostatic_drug_given as @cytostatic_drug_given" do
        cytostatic_drug_given = CytostaticDrugGiven.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CytostaticDrugGiven.any_instance.stub(:save).and_return(false)
        put :update, {:id => cytostatic_drug_given.to_param, :cytostatic_drug_given => {}}, valid_session
        assigns(:cytostatic_drug_given).should eq(cytostatic_drug_given)
      end

      it "re-renders the 'edit' template" do
        cytostatic_drug_given = CytostaticDrugGiven.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CytostaticDrugGiven.any_instance.stub(:save).and_return(false)
        put :update, {:id => cytostatic_drug_given.to_param, :cytostatic_drug_given => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cytostatic_drug_given" do
      cytostatic_drug_given = CytostaticDrugGiven.create! valid_attributes
      expect {
        delete :destroy, {:id => cytostatic_drug_given.to_param}, valid_session
      }.to change(CytostaticDrugGiven, :count).by(-1)
    end

    it "redirects to the cytostatic_drug_givens list" do
      cytostatic_drug_given = CytostaticDrugGiven.create! valid_attributes
      delete :destroy, {:id => cytostatic_drug_given.to_param}, valid_session
      response.should redirect_to(cytostatic_drug_givens_url)
    end
  end

end
