class CytostaticDrug < ActiveHash::Base
  self.data = [
    {id:  1, number: 100, name: "Mustin"},
    {id:  2, number: 101, name: "Leukeran/Chlorambucil"},
    {id:  3, number: 102, name: "Alkeran/Melfalan"},
    {id:  4, number: 103, name: "Sendoxan/Cyklofosfamid/Alexan i.v."},
    {id:  5, number: 104, name: "Prednimustine"},
    {id:  6, number: 105, name: "Sendoxan/Cyklofosfamid p.o."},
    {id:  7, number: 107, name: "Ifosfamid/Holoxan"},
    {id:  8, number: 120, name: "BCNU/Carmustine"},
    {id:  9, number: 121, name: "CCNU/Lomustine"},
    {id: 10, number: 130, name: "Temodal"},
    {id: 11, number: 140, name: "Myleran/Busulfan"},
    {id: 12, number: 160, name: "Tifosfyl/Thiotepa"},
    {id: 13, number: 170, name: "Treosulfan"},
    {id: 14, number: 200, name: "Methotrexat intrathecalt"},
    {id: 15, number: 201, name: "Methotrexat peroralt"},
    {id: 16, number: 202, name: "Methotrexat intravenöst"},
    {id: 17, number: 203, name: "Lanvis/Thioguanin"},
    {id: 18, number: 204, name: "Methotrexat intramuskulärt"},
    {id: 19, number: 221, name: "Purinethol/6-Merkaptopurin"},
    {id: 20, number: 223, name: "Azathioprin"},
    {id: 21, number: 240, name: "5-Fluorouracil"},
    {id: 22, number: 241, name: "Cytosar/Depocyte intrathecalt"},
    {id: 23, number: 242, name: "Cytosar intravenöst"},
    {id: 24, number: 244, name: "Fludarabin"},
    {id: 25, number: 245, name: "2-chlorodeoxyadenosin/2-CDA"},
    {id: 26, number: 300, name: "Cosmegen/Actinomycin-D"},
    {id: 27, number: 301, name: "Bleomycin"},
    {id: 28, number: 302, name: "Adriamycin/Doxorubicin"},
    {id: 29, number: 303, name: "Mitomycin-C"},
    {id: 30, number: 304, name: "Cerubidin/Rubidomycin/Daunorubicin/Daunoxome"},
    {id: 31, number: 305, name: "Mitramycin"},
    {id: 32, number: 307, name: "Epirubicin/Farmorubicin"},
    {id: 33, number: 308, name: "Mitoxantrone/Novantrone"},
    {id: 34, number: 310, name: "Idarubicin/Zavedos"},
    {id: 35, number: 320, name: "Amsakrin/Amekrin"},
    {id: 36, number: 400, name: "Hydrea/Hydroxyurea"},
    {id: 37, number: 401, name: "Procarbazin/Natulanar"},
    {id: 38, number: 402, name: "DTIC/Dacarbazin"},
    {id: 39, number: 403, name: "Asparaginas"},
    {id: 40, number: 404, name: "Dibromodulcitol/Mitolactol"},
    {id: 41, number: 405, name: "Etoposid/Vepesid/VP-16 i.v."},
    {id: 42, number: 406, name: "VM-26/Vumon/Teniposid"},
    {id: 43, number: 407, name: "Cisplatinol/Platinol"},
    {id: 44, number: 408, name: "Etoposid/Vepesid/VP-16 p.o."},
    {id: 45, number: 409, name: "Hexametylmelamin"},
    {id: 46, number: 410, name: "Metyl-GAG"},
    {id: 47, number: 430, name: "Interferon-alfa"},
    {id: 48, number: 431, name: "PEG-Interferon-alfa"},
    {id: 49, number: 440, name: "Mabthera/Retuximab"},
    {id: 50, number: 445, name: "Enbrel/TNF-blockare"},
    {id: 51, number: 460, name: "Velbre/Vinblastin"},
    {id: 52, number: 461, name: "Vincristin/Oncovin"},
    {id: 53, number: 462, name: "Vindesin/Eldisin"},
    {id: 54, number: 463, name: "Paraplatin/Carboplatin/JM8"},
    {id: 55, number: 464, name: "Vinorelbin/Navelbine"},
    {id: 56, number: 470, name: "Topotecan/Hycamtin"},
    {id: 57, number: 475, name: "Irinotecan"},
    {id: 58, number: 480, name: "Iressa"},
    {id: 59, number: 481, name: "Sterecyt"},
    {id: 60, number: 485, name: "Imatinib/Glivec"},
    {id: 61, number: 490, name: "Gemzar/Gemcitabine"},
    {id: 62, number: 491, name: "Mylotarg/Gemtuzumab"},
    {id: 63, number: 494, name: "Taxotere/Docetaxel"},
    {id: 64, number: 495, name: "Spirogermanium"},
    {id: 65, number: 496, name: "Tamoxifen p.o."},
    {id: 66, number: 497, name: "A-vitamin/Vesanoid/Retinoic acid"},
    {id: 67, number: 498, name: "Lysodren/Mitotan"},
    {id: 68, number: 499, name: "PEG-Asparaginase/Oncaspar"},
    {id: 69, number: 500, name: "Corticosteroid/Hydrocortison"},
    {id: 70, number: 511, name: "Prednison/Deltison"},
    {id: 71, number: 521, name: "Prednisolon"},
    {id: 72, number: 530, name: "Betapred/Betametazon"},
    {id: 73, number: 541, name: "Dekadron/Dexametazon"},
    {id: 74, number: 441, name: "Avastin/Bevacizumab"},
    {id: 75, number: 432, name: "PEG-Interferon-beta"},
    {id: 76, number: 420, name: "Interferon-beta"}

  ]
  def cytostatic_drug_combo
    "#{self.number} - #{self.name}"
  end
end

